#!/usr/bin/env python3
# -*- utf-8 -*-

import sys
import generator

argv = sys.argv

# -----------------------------
# Constant Varibales
# -----------------------------
USAGE = '''USAGE: {} command [command options...]'''.format(argv[0])
HELP = '''Commands:
\tgen\t\tgenerate contest directory and files.
'''
NO_COMMANDS = '''ERROR: {command} is invaid command.'''
COMMANDS = {
    'gen': generator.generate,
}

if __name__ == "__main__":
    # -----------------------------
    # Varidate Arguments
    # -----------------------------
    if len(argv) < 2:
        print(USAGE)
        print(HELP)
        sys.exit(1)

    command = argv[1].lower()
    if command not in COMMANDS:
        print(NO_COMMANDS.format(command=command))
        print(HELP)
        sys.exit(1)

    executor = COMMANDS[command]
    exit_code = executor(argv[1:])

    sys.exit(exit_code)
